### ISSUE TITLE
Вёрстка стр. Login/Register

### ISSUE THREAD

**Issue by nicothin** [nicothin/nesia#10]
http://nicothin.pro/nesia/login.html
http://nicothin.pro/nesia/reg-01.html
http://nicothin.pro/nesia/reg-02a.html
http://nicothin.pro/nesia/verify.html

Незначительные отличия по отступам (и для «Forget password?» по кеглю) для сохранения стилей готовых элементов (не плодил сущности без надобности).
Состояния по умолчанию (не ошибки) — убиранием классов-модификаторов (классы с `--error` в названии).

Не запилил модальное окно с селектором области фото.
Вопрос к @markxploder: какой инструмент там планируется использовать? Есть мне смысл искать какой-то плагин для jQuery (он на проекте сейчас) для подобного?

**Comment by vladimir075** [comment]
Николай, я видимо пропустил это в дизайне, прошу сделать небольшую правку.
Вот здесь есть поле Full name http://nicothin.pro/nesia/reg-02a.html Прошу сделать вместо одного два поля 1) First name 2) Last name 
 Оба со звездочками обязательности

**Comment by nicothin** [comment]
Сделано.

**Comment by nicothin** [comment]
из чата в телеге: плагин для кадрирования аватара — https://fengyuanchen.github.io/cropper/

**Comment by vladimir075** [comment]
то есть верстать ничего не надо и работа по верстке закончена?

**Comment by nicothin** [comment]
> то есть верстать ничего не надо и работа по верстке закончена?

нет, нужно доверстать модальное окно и написать функциональность «выбор файла → открытие модального окна → включение кроппера», как минимум.

в работе.

**Comment by vladimir075** [comment]
аа, спасибо

**Comment by nicothin** [comment]
Добавил интерфейс выбора картинки пользователя.
Посмотреть можно на http://nicothin.pro/nesia/reg-02a.html

**Comment by vladimir075** [comment]
Николай, хотел попросить сделать еще один вариант этой рамки и надписи обычным цветом, не красным. Возможно не будем делать загрузку фото обязательной. 
![Screen Shot 2021-03-19 at 3 13 20 PM](https://user-images.githubusercontent.com/17883276/111785901-dba6ab00-88c5-11eb-98bd-ef66a4b0c4f3.png)

**Comment by vladimir075** [comment]
Николай, прошу сделать еще один вариант логина регистрации модальными окнами

**Comment by nicothin** [comment]
Готово.
В коде оставил комментарии о вариациях этих элементов.
Цвет текста определяется классом `b-user-photo--error` на родителе, цвет кнопки — классом на лейбле, стилизованном под кнопку: если там написан `b-btn-2--secondary`, то кнопка с красной рамкой (типовая, встречается в других местах), а если там `b-btn-2--gray`, то «серая» кнопка, бордюр которой выглядит и реагирует на наведение так же, как текстовые поля ниже.

```html
<form action="" class="b-form-2  b-auth__form">
  <!-- b-user-photo--error — добавить для того, чтобы сделать текст красным -->
  <div class="b-user-photo  b-auth__add-photo">
    <img id="userpic-image" src="img/photo_empty.svg" alt="%USERNAME%" class="b-user-photo__img" width="80" height="80">
    <div class="b-user-photo__info">
      <!-- b-btn-2--secondary -->
      <label class="b-btn-2  b-btn-2--block  b-btn-2--gray">
        <input type="file" accept="image/*" onchange="loadFile(event)">
        Add photo
      </label>
      <p class="b-user-photo__descr">Photo is mandatory, it increase confidence of other users</p>
    </div>
  </div>
  ...
```

**Comment by nicothin** [comment]
> Николай, прошу сделать еще один вариант логина регистрации модальными окнами

Сделал: положил блочки регистрационных страниц в отдельные модалки. Добавил на http://nicothin.pro/nesia/login.html (под заголовок) ссылки, клик по которым открывает модалки.

Если нужно в одном модальном окне реализовать «шаги регистрации», можно сделать еще одно модальное окно с разметкой по принципу:

```html
<div class="modal  b-modal-2  fade" tabindex="-1" role="dialog" id="УНИКАЛЬНЫЙ_ИДЕНТИФИКАТОР">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-body">
        <div class="b-auth__inner">
          <div class="НЕКАЯ_ОБЁРТКА_ДЛЯ_ПОКАЗА_ИЛИ_СОКРЫТИЯ">
            <!-- <h3 class="b-main-header  b-main-header--content  b-auth__title">ЗАГОЛОВОК</h3> -->
            <!-- форма -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```
И внутри обёртки вкопипастить разметку любого «шага» (или вообще что угодно).
Управление модалками было когда-то (еще до меня) сделано на бутстрапе 3.3.6 (изменена только стилизация). Доку по работе с этими модалками из JS можно найти тут: https://getbootstrap.com/docs/3.3/javascript/#modals
