### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by vladimir075** [nicothin/nesia#12]
![Screen Shot 2021-03-03 at 4 31 54 PM](https://user-images.githubusercontent.com/17883276/109820819-080fc580-7c3e-11eb-85f5-9a0da36666c6.png)
Николай, нигде не вижу шапки в залогиненном состоянии юзера. Аватар, колокольчик, нотификации (скрытые/открытые). Это где то есть? Также меню с аватаром

**Comment by vladimir075** [comment]
Есть также ряд других экранов, которые не могу найти в верстке. Приведу линками на фигму
1) Состояния https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=333%3A688
2) https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=18%3A116 есть страница my listings, но не вижу всех ее элементов согласно дизайну
3) Состояние Connect with https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=119%3A174
4) https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=267%3A914

**Comment by nicothin** [comment]
**Авторизация**
Скрыта в разметке стилями

![image](https://user-images.githubusercontent.com/3499680/109947586-89bd2d00-7cea-11eb-87cc-e0ce3fc3d90d.png)

**Состояния в сайдбаре локации** 
Скрыты стилями.

![image](https://user-images.githubusercontent.com/3499680/109948326-431c0280-7ceb-11eb-9b93-b50db0a2c932.png)

**my listings**
Тут, насколько понимаю, вопрос в модалках-попапах, в нижнем правом углу. Вот они:

https://user-images.githubusercontent.com/3499680/109949219-27652c00-7cec-11eb-8d82-23ce2f408ad3.mp4

**Состояние Connect with**
Тоже было скрыто, но кнопкой, ибо текст не менялся. Было неочевидно, так что я продублировал блок в указанном состоянии, теперь он показан в самом низу на https://nicothin.pro/nesia/auction.html

**Удачная смена пароля**
Аналогично, скрыта стилями.

![image](https://user-images.githubusercontent.com/3499680/109950571-b58de200-7ced-11eb-9e88-6b72efc5a0d7.png)

**Comment by vladimir075** [comment]
Николай, а вот эти состояния на карточке объекта где скрыты?https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=0%3A1
![Screen Shot 2021-03-23 at 6 02 44 PM](https://user-images.githubusercontent.com/17883276/112178070-298f1c00-8c02-11eb-9cae-91662aaed390.png)

**Comment by nicothin** [comment]
> Николай, а вот эти состояния на карточке объекта где скрыты?https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=0%3A1

Это на странице https://nicothin.pro/nesia/item.html, по месту. В блоке меняется часть справа от заголовка, в коде там показан один блок, прочие скрыты стилями. При оживлении нужно выводить там нужный вариант блока с классом `b-info__price-change-wrap`:

![image](https://user-images.githubusercontent.com/3499680/112748066-0ed1f400-8fc2-11eb-97ee-d15dd5bdf60d.png)

Я сейчас продублирую ведь крупный блок «Аукцион» в трех вариантах, чтоб было очевиднее.

**Comment by nicothin** [comment]
Есть.
Теперь на https://nicothin.pro/nesia/item.html подряд показаны все варианты блока «Аукцион».
