### ISSUE TITLE
Accept cookie banner

### ISSUE THREAD

**Issue by vladimir075** [nicothin/nesia#13]
Николай, добрый день. Поздравляю Вас с Новым Годом и днем рожденья! @nicothin 
Хотел попросить сверстать для Терры баннер Accept cookie. В дизайне у нас его нет, но наверное именно его не сложно и без дизайна сделать. Пример того, что хотелось бы вот здесь 
![Screen Shot 2022-01-10 at 12 08 16 PM](https://user-images.githubusercontent.com/17883276/148748742-6f57ef78-3ae9-4965-b74f-bc56390af111.png)
Я бы добавил туда еще справа наверху белый крестик закрытия и и убрал надпись do not accept (то есть останется текст с гиперлинком и крестиком закрытия и кнопка Accept.
В десктопе чтобы он появлялся у нас в левом нижнем углу (не в правом!). Ну а в мобильном внизу. 
Заранее спасибо.

**Comment by nicothin** [comment]
@vladimir075 ok, сегодня вечером планирую сделать. Отпишусь в Новом ишью.

**Comment by nicothin** [comment]
https://nicothin.pro/nesia/favorites.html — сделал небольшой блок на основе уже существующего в проекте.
Разметка во всех файлах с подвалом, она такая:
```
    <div class="b-info-bottom  b-info-bottom--cookies  b-info-bottom--invert">
      <div class="b-info-bottom__inner">
        <button type="button" class="close  b-info-bottom__close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="b-info-bottom__text">Далеко-далеко за словесными горами в стране гласных и согласных, живут рыбные тексты. За заманивший лучше которое переписывается от всех выйти большого рекламных, подзаголовок она, риторический <a href="#">меня семь живет жизни не</a>. Lorem, ему продолжил.</div>
        <div class="b-info-bottom__btn  b-info-bottom__btn--single-btn-right">
          <button class="b-btn-2  b-btn-2--secondary   b-btn-2--block-md">Кнопка</button>
        </div>
      </div>
    </div>
```
Стили немного дополнены: https://github.com/nicothin/nesia/commit/5842367409e06122aa04387d4f7856540cbf7b29#diff-5a44ee9d7462243f493cd012d20df40c89da49bf089e086d7bf2daa787186896

**Comment by vladimir075** [comment]
а можно крестик чуть больше и кнопку в мобильном чуть больше? ненамного

**Comment by nicothin** [comment]
https://nicothin.pro/nesia/add.html - старый вариант
https://nicothin.pro/nesia/auction.html - вариант с чуть увеличенными крестиком и кнопкой

[Стили ](https://github.com/nicothin/nesia/blob/gh-pages/css/style-18-spring.min.css)дополнены

Разметка второго варианта незначительно отличается:
```
<div class="b-info-bottom  b-info-bottom--cookies  b-info-bottom--invert">
  <div class="b-info-bottom__inner">
    <button type="button" class="close  b-info-bottom__close  b-info-bottom__close--lg" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <div class="b-info-bottom__text">Далеко-далеко за словесными горами в стране гласных и согласных, живут рыбные тексты. За заманивший лучше которое переписывается от всех выйти большого рекламных, подзаголовок она, риторический <a href="#">меня семь живет жизни не</a>. Lorem, ему продолжил.</div>
    <div class="b-info-bottom__btn  b-info-bottom__btn--single-btn-right">
      <button class="b-btn-2  b-btn-2--secondary  b-btn-2--block-md  b-btn-2--lg">Кнопка</button>
    </div>
  </div>
</div>
```

**Comment by vladimir075** [comment]
@greeceruit Олег, прошу внедрить вариант с увеличенными кнопкой и крестиком
только у меня тут глюк какой то появляется в виде надписи login
![Screen Shot 2022-01-16 at 12 32 43](https://user-images.githubusercontent.com/17883276/149656493-925ffd9a-b481-4074-9276-74379a84dc7e.png)
@nicothin это откуда?
