### ISSUE TITLE
Верстка модального окна регистрации.

### ISSUE THREAD

**Issue by vladimir075** [nicothin/nesia#14]
Николай, у нас есть форма регистрации отдельной страницей, но также нам пришлось сделать еще одну форму модальным окном. 
![Screen Shot 2022-01-10 at 12 42 12 PM](https://user-images.githubusercontent.com/17883276/148752991-3eaf8bcf-7389-4938-a513-20f94743d429.png)

Олег сам сверстал ее, но я бы хотел попросить сделать ее правильно.
1) Симметричные красивые расстояния
2) Добавить маленьким шрифтом надпись By signing up, I accept Terranesia Terms of Service and acknowledge the Privacy Policy (с гиперссылками) 

**Большая проблема у на также здесь в том, что модальное окно не скролируется а эта форма не помещается во всех девайсах. Как это можно решить?**

Также вот здесь надо отцентровать кнопку Facebook и сделать ее на ширину одинаковую с кнопкой Next
![Screen Shot 2022-01-10 at 12 19 55 PM](https://user-images.githubusercontent.com/17883276/148750345-d83eb59a-d91b-4468-a263-76714ce711ff.png)

На регистрации, которая через страницу, а не через модальное, тоже посмотреть все ли симметрично и правильно. Например, мне кажется там чуть съезжает разделяющая код полоса в поле телефона.
https://el.terranesia.com/signup/

**Comment by nicothin** [comment]
Это смогу взять в работу в ЧТ или ПТН, до ПН, видимо, сделаю.

**Comment by vladimir075** [comment]
Отлично, спасибо. А как решается вопрос с тем что форма большая, далеко не везде в мобилах поместится и при это модальное окно не скролируется? Или можно заставить его скролироваться?

**Comment by vladimir075** [comment]
И вот здесь немного причесать
https://en.terranesia.com/login/
![Screen Shot 2022-01-14 at 2 48 27 PM](https://user-images.githubusercontent.com/17883276/149517934-588c1c4a-13ec-4a03-ae6f-b9741e1ff7b4.png)
Forgot your password надо разместить под полем пароля с правого края напротив Remember me 
Sign in кнопку сделать на ширину верхних полей
Перед надписью Don't have an account... дать отступ в одну строку
Кнопку фб поставить симметрично верхнему краю поля email
Аналогично в мобильной версии только здесь еще дать черточку перед кнопкой fb с надписью or continue with (как на скриншоте в комменте выше)
![Screen Shot 2022-01-14 at 2 55 13 PM](https://user-images.githubusercontent.com/17883276/149518696-30348208-4a6e-49f2-8001-696436a2d4ec.png)

**Comment by nicothin** [comment]
@vladimir075 не могу понять как вызвать модалки регистрации/подтвержения-мыла/вставки пароля :(
Подскажите.

**Comment by nicothin** [comment]
>Олег сам сверстал ее, но я бы хотел попросить сделать ее правильно.

>Симметричные красивые расстояния
Добавить маленьким шрифтом надпись By signing up, I accept Terranesia Terms of Service and acknowledge the Privacy Policy (с гиперссылками)

Нужно уточнение: какие расстояния не нравятся? (я вижу проблему только с недостаточным нижним внутренним отступом модалки)

**Comment by nicothin** [comment]
>Большая проблема у на также здесь в том, что модальное окно не скролируется а эта форма не помещается во всех девайсах. Как это можно решить?

В верстке, при эмуляции, скроллируется.
Вы смотрите реальное устройство и уже внедренную версию? Если так, мне важно знать что, на каком устройстве, в каком браузере.

**Comment by vladimir075** [comment]
> @vladimir075 не могу понять как вызвать модалки регистрации/подтвержения-мыла/вставки пароля :( Подскажите.

Если, в незалогиненном состоянии на терре, Вы откроете любую карточку объекта и нажмете например save to favourites, то выйдет модальное окно запроса мейла. Если введете туда мейл, который был ранее зарегистрирован, выйдет модальное запроса пароля. Если введете мейл, который ранее зарегистрирован не был, то выйдет форма регистрации.

**Comment by nicothin** [comment]
>Также вот здесь надо отцентровать кнопку Facebook и сделать ее на ширину одинаковую с кнопкой Next

Нашел на сайте: любой объект (/i/28478876/), ткнуть кнопку "Спросить собственника"

В верстке поправил кнопку:
![image](https://user-images.githubusercontent.com/3499680/149655287-1a95e7b6-93a0-4c2c-b8f0-a124a33af0e7.png)

Кнопка вынесена из списка (сам список закомментирован), изменился один класс на кнопке: https://github.com/nicothin/nesia/commit/7f372b5d64e4672c0adf4483ee5674f5afd58402

**Comment by vladimir075** [comment]
> > Большая проблема у на также здесь в том, что модальное окно не скролируется а эта форма не помещается во всех девайсах. Как это можно решить?
> 
> В верстке, при эмуляции, скроллируется. Вы смотрите реальное устройство и уже внедренную версию? Если так, мне важно знать что, на каком устройстве, в каком браузере.

Да, реальное и уже внедренную версию. У меня например не скролируется в iphone SE, кажется восьмерка. Но насколько я понял, Олег говорит что модальные окна не скролируются в мобильниках вообще... Сейчас у меня правда оно и помещается, но если добавим туда terms & conditions итд? Да и потом у меня то достаточно большой экран. @greeceruit Олег, прокомментируй

**Comment by vladimir075** [comment]
> > Также вот здесь надо отцентровать кнопку Facebook и сделать ее на ширину одинаковую с кнопкой Next
> 
> Нашел на сайте: любой объект (/i/28478876/), ткнуть кнопку "Спросить собственника"
> 
> В верстке поправил кнопку: ![image](https://user-images.githubusercontent.com/3499680/149655287-1a95e7b6-93a0-4c2c-b8f0-a124a33af0e7.png)
> 
> Кнопка вынесена из списка (сам список закомментирован), изменился один класс на кнопке: [7f372b5](https://github.com/nicothin/nesia/commit/7f372b5d64e4672c0adf4483ee5674f5afd58402)

отцентровано шикарно, только я модалку не узнаю. у меня на внедренной версии она выглядит вот так 
![IMG_3017](https://user-images.githubusercontent.com/17883276/149655577-95b64e85-5a14-48b7-9d4d-dae0938da83d.jpg)

**Comment by vladimir075** [comment]
> > Олег сам сверстал ее, но я бы хотел попросить сделать ее правильно.
> 
> > Симметричные красивые расстояния
> > Добавить маленьким шрифтом надпись By signing up, I accept Terranesia Terms of Service and acknowledge the Privacy Policy (с гиперссылками)
> 
> Нужно уточнение: какие расстояния не нравятся? (я вижу проблему только с недостаточным нижним внутренним отступом модалки)

не знаю может и нормальные расстояния, посмотрите своим взглядом, нужно ли что-то поправить. в любом случае надо добавить текст с гиперссылками, о котором я писал выше про terms & conditions, privacy policy 
Еще там кажется в полях ввода телефона и кода что то сбивается не симметрично (разделяющая код палочка)

**Comment by greeceruit** [comment]
> Да, реальное и уже внедренную версию. У меня например не скролируется в iphone SE, кажется восьмерка. Но насколько я понял, Олег говорит что модальные окна не скролируются в мобильниках вообще... Сейчас у меня правда оно и помещается, но если добавим туда terms & conditions итд? Да и потом у меня то достаточно большой экран. @greeceruit Олег, прокомментируй

На днях в каком-то шаблоне (cuba admin template) на bootstrap видел пример модального окна со скролом. Так что, наверное, можно сделать...

**Comment by nicothin** [comment]
>На регистрации, которая через страницу, а не через модальное, тоже посмотреть все ли симметрично и правильно. Например, мне кажется там чуть съезжает разделяющая код полоса в поле телефона.
https://el.terranesia.com/signup/

Точно, по вертикали полоска у телефона не согласована с цифрами, если до полоски нет цифры. 
![image](https://user-images.githubusercontent.com/3499680/149655426-dd2d2a1b-5871-403a-941d-9b8bceb15aec.png)

[Скорректировано стилями](https://github.com/nicothin/nesia/commit/9662c40e81a33458e72266fa47a4c6f3168ca2c4#diff-5a44ee9d7462243f493cd012d20df40c89da49bf089e086d7bf2daa787186896).

**Comment by nicothin** [comment]
# Задачи

Задача 1. Форма регистрации в модальном окне: нужно уточнить что именно менять

Задача 2. Все модальные окна: проверить/обеспечить скроллируемость на Safari (реального устройства нет, провреить смогу только на старом айпаде и макбуке)

Задача 3. Модалка c логином (с кн. авторизации через FB) -- кнопку растянуть

Задача 4. Стр. https://en.terranesia.com/login/: Forgot your password надо разместить под полем пароля с правого края напротив Remember me. Сделать зеленым цветом. Sign in кнопку сделать на ширину верхних полей
Перед надписью Don't have an account... дать отступ в одну строку
Кнопку фб поставить симметрично верхнему краю поля email
Аналогично в мобильной версии только здесь еще дать черточку перед кнопкой fb с надписью or continue with (как на скриншоте в комменте выше)

Задача 3 выполнена, смена разметки может быть применена в любой внедренной модалке: кнопка вынесена из списка `<ul class="b-social__list">` (сам список закомментирован), изменился один класс на кнопке: был `b-btn--fb`, стал `b-btn--fb-block`/ См. https://github.com/nicothin/nesia/commit/7f372b5d64e4672c0adf4483ee5674f5afd58402

**Comment by nicothin** [comment]
Задача 1 
Применены перебивающие стили из https://en.terranesia.com/static/css/alekos.css?ver=1.008-20211228, поэтому внешний вид отличается от вёрстки, в частности, отступы между полями (видимо, чтобы влезли без скролла).
Для добавления текста достаточно вставить над кнопкой вот эти три строки: https://github.com/nicothin/nesia/commit/6ae3f105ce1869405c2b85a686b35d9c44007cbc#diff-eecb13abc7e8b7d2db0289bf85291cf27c31ecca3529e3ec8e345dc3e8425067R456-R458

Со старыми стилями (без перебивающих, упомянутых выше) выглядит так:
![image](https://user-images.githubusercontent.com/3499680/149671644-84797e8a-8865-420d-ab3e-574a3f91ad0c.png)

**Comment by greeceruit** [comment]
@nicothin , да, я пытался впихнуть всё по возможности в меньшую высоту.

**Comment by nicothin** [comment]
Задача 2
верстка и сама терранезия: модалки скроллятся, если не влезли в экран настольного сафари.
мобильный сафари на айфоне SE - тоже скроллится.

Это значит, что я не смогу найти и решить проблему с отсутствием скролла при переполнении модального окна :(

**Comment by vladimir075** [comment]
@greeceruit прошу посмотреть что сделано Николаем и остались ли к нему какие то вопросы по задачам выше.
