### ISSUE TITLE
Переверстать кнопки сообщений в мессенджере профиля

### ISSUE THREAD

**Issue by vladimir075** [nicothin/nesia#15]
Здесь нам надо подключить Олега, чтобы он прояснил, в чем именно сложности. Николай, прошу послать ему приглашение присоединиться на alekos@greece.ru

**Comment by nicothin** [comment]
Отправил приглашение @greeceruit 
Нужна формализация задачи и сложностей. Видимо, чат сторонней разработки и сложность с контролем стилей этого встроенного инструмента из стилей проекта?

**Comment by greeceruit** [comment]
На странице http://nicothin.pro/nesia/my-listings.html в списке юзеров, которые сохранили объект недвижимости в "Избранное", в ячейке таблицы с классом b-stats-2__user-table-action при наведении мыши появляется кнопка  надписью Contact или Open message. На узком экране кнопка в __user-table-action уже не появляется и, получается, что владелец объекта недвижимости не может обратиться к юзеру из мобильного интерфейса.

Я, в качестве временного решения, переставил местами ячейки b-stats-2__user-table-action и b-stats-2__user-table-date и изменил им классы. Теперь кнопка Contact видна и в мобильном, и в десктопном режиме, но, наверное, как-то её нужно облагородить. По меньшей мере, кнопка Open message с маркером новых сообщений выглядит намного хуже - кусок маркера съедается...   

[https://www.youtube.com/watch?v=U8B6FPbDuss](видео)

**Comment by vladimir075** [comment]
вставлю свои пять копеек )) думаю что не появляются эти кнопки не из за узости экрана, а из за того, что в мобиле нет такого понятия как наведение мыши, а сверстано это дело по изначальной задумке именно так. Вообще я совсем не против, чтобы кнопки эти были видны постоянно и в десктопе и в мобиле, то есть вообще убрать понятие их "появления при наведении мыши". Может быть так будет даже лучше для юзеров.

**Comment by nicothin** [comment]
В целом, методика тестирования, с которой записано видео (сужением браузера), некорректна, т.к. не происходит переключения на тач-интерфейс. Для тач-интерфейса ячейка с кнопками показывается всегда, кроме самой малой ширины. На скрине ниже я переключил тип интерфейса на тач, заметно, что обе "строки" показали свои кнопки:
![image](https://user-images.githubusercontent.com/3499680/149652319-57ba94fb-5964-45a7-8fd5-b1d96f7383d6.png)

Если верно помню, я выражал озабоченность тем, что в мобилке эти кнопки не показываются вовсе. Но чем окончилось обсуждение не помню и найти его не могу. А может, память подводит, и не выражал :(

Пока я пришел к такому решению: на ширина 479 (и менее) показывать кнопки действий для любого типа интерфейса (тач/не-тач) под аватарой и именем:
![image](https://user-images.githubusercontent.com/3499680/149652900-ed1b950f-a414-4f22-841a-d8c93d6bcf98.png)

При этом, если имя указано длинное, дата будет смещена вниз (побочный эффект смены стилей без переписывания разметки, этого можно избежать фиксацией максимальной длины имени в процентах ширины "строки" с именем и датой, однако неизвестна длина даты, такая фиксация периодически "стреляет в ногу"):
![image](https://user-images.githubusercontent.com/3499680/149652943-22229f75-cff3-4e1b-9074-2e0c3291be29.png)

[Все изменения](https://github.com/nicothin/nesia/commit/2f3ec8ea6a7995f8ac4e47040520f537bde406bc#diff-5a44ee9d7462243f493cd012d20df40c89da49bf089e086d7bf2daa787186896) только стилевые, разметку никак не менял.
Затронутые стилевые классы используются только на стр. my-listings.html, никакие другие страницы вёрстки не изменятся.

**Comment by vladimir075** [comment]
Думаю что надо просто показывать эти сообщения везде, в том числе и в десткопе, убрав совсем эффект наведения мыши. Про мобилу ситуация такая. во первых показывать число, в мобиле, на мой взгляд излишне. во вторых мы там не выводим фамилий. Если само имя длинное и без фамилии, то можно ведь ограничить вывод количества символов? Я к тому, что если эти факторы помогут кнопки расположить напротив аватара, а не под ним, лучше наверное так и сделать...
