### ISSUE TITLE
Правки Январь 2022

### ISSUE THREAD

**Issue by vladimir075** [nicothin/nesia#16]
https://docs.google.com/document/d/1WBezQLtJg2klFK-1phCGpng1IA042a125nO3CSh3yLo/edit?usp=sharing
Коллеги, выше в документе некоторые дополнительные фичи для Терры. В начале документа собственно сами задачи, которые были поставлены дизайнеру, ниже реализация их дизайнером со ссылкой на фигму.
Прошу посмотреть, если есть какие вопросы, готов ответить.
Николай, у Олега есть какие то пожелания по верстке, Олег, прошу обозначить.
@nicothin @greeceruit

**Comment by nicothin** [comment]
Отсмотрел, почти все понял (кое-где ссылки на фигму с очень общим планом, мелкие вопросы точно возникнут по ходу изменения вёрстки).
@greeceruit какие пожелания? Я при выполнении декомпозирую на несколько мелких задач, которые и буду поэтапно сдавать.

**Comment by greeceruit** [comment]
> Отсмотрел, почти все понял (кое-где ссылки на фигму с очень общим планом, мелкие вопросы точно возникнут по ходу изменения вёрстки). @greeceruit какие пожелания? Я при выполнении декомпозирую на несколько мелких задач, которые и буду поэтапно сдавать.

Не совсем пожелания... Я бы сказал надежда :)   На то, что при возможности всё будет решено путём минимальных изменений в уже внедрённую разметку.

**Comment by vladimir075** [comment]
@greeceruit Олег так скромно отписался по вопросу пожеланий, но если я правильно понимаю, для него это критично, потому что иначе начинают ломаться уже внедренные фичи и время разработки существенно увеличивается )

**Comment by nicothin** [comment]
@vladimir075 пока получается, что до ПН (28 02) я могу это успеть, если вопросов не будет.

**Задача 1** выполнена
Фигма: https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=0%3A1 (3 экрана, 2 модалки)
Коммиты: https://github.com/nicothin/nesia/commit/893af35ed38e135dcbfbe9613764fb7cb793e239 — исходник, https://github.com/nicothin/nesia/commit/a72240447c504bf90478df20fe72f63dbabd48a5 — в сборке
Минимизировал изменения, использовал максимум того, что есть в проекте (календарь из jquery UI, модалки, которые уже должны быть внедрены).
Демо: https://nicothin.pro/nesia/messages.html — жать «Sorry, it does not anymore» и потом «It already rented»

**Comment by nicothin** [comment]
@greeceruit я это все делаю в начальной вёрстке и ОЧЕНЬ надеюсь, что расхождение с внедренным кодом минимально. Это так?

**Comment by nicothin** [comment]
@vladimir075 в задаче есть часть про изменение формы. Но на стр https://ru.terranesia.com/object/add/ я вижу форму, сильно отличную от макета из задачи (https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=2753%3A1353)

Насколько понимаю, я должен обеспечить вывод следующих блочков:
![image](https://user-images.githubusercontent.com/3499680/155187563-e7d6fbfa-b35f-47b5-97d6-a93b5dadab56.png)

Их в готовой верстке нет, так что ограничений, по идее, тоже нет. @greeceruit может, я не прав?

**Comment by nicothin** [comment]
Задача 2 (изменение формы)

Коммит: https://github.com/nicothin/nesia/commit/6d38e1f24b70dbb05137dc7b5056f8e1b554830e
Для демо я убрал мешающие блоки со [страницы добавления](https://nicothin.pro/nesia/add.html)

Календарь имеет стили, которые у него в проекте по умолчанию (не делал белым)

@vladimir075 @greeceruit проверьте пожалуйста.

**Comment by vladimir075** [comment]
> @vladimir075 в задаче есть часть про изменение формы. Но на стр https://ru.terranesia.com/object/add/ я вижу форму, сильно отличную от макета из задачи (https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=2753%3A1353)
> 
> Насколько понимаю, я должен обеспечить вывод следующих блочков: ![image](https://user-images.githubusercontent.com/3499680/155187563-e7d6fbfa-b35f-47b5-97d6-a93b5dadab56.png)
> 
> Их в готовой верстке нет, так что ограничений, по идее, тоже нет. @greeceruit может, я не прав?

да там эти штуки в процедуру занесения объекта надо добавить. с технической точки зрения вопросы наверное к Олегу @greeceruit

**Comment by greeceruit** [comment]
> @greeceruit я это все делаю в начальной вёрстке и ОЧЕНЬ надеюсь, что расхождение с внедренным кодом минимально. Это так?

Вёрстку я старался не менять... Может, продублировал какие-то дивы и модалки. Постараюсь внедрить изменения. Если столкнусь с сильными расхождениями, подумаем, как решить....

**Comment by nicothin** [comment]
>Нужно будет родительский контейнер блока с описанием реализовать так, чтобы я мог динамически на JS добавлять в этот контейнер нужное количество блоков с описаниями на других языках.

@greeceruit 
Ясно. Сейчас чуть переработаю этот блок с описанием, чтобы их могло быть сколько угодно и JS, обеспечивающий дропдаун языка и счётчик символов, корректно работал. 
В интерфейсе, кстати, не вижу возможности добавить еще один блочок описания, мне для этого что-то добавить?

**Comment by vladimir075** [comment]
_В интерфейсе, кстати, не вижу возможности добавить еще один блочок описания, мне для этого что-то добавить?_
Если я правильно понял, что этот вопрос относится к дизайну, тот вот здесь все есть https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=2740%3A1509
Напомню, что в целом текущие задачи по Терре изложены вместе со ссылками на макеты в нижней части документа с заголовком Реализация дизайна от Надежды [ ](https://docs.google.com/document/d/1WBezQLtJg2klFK-1phCGpng1IA042a125nO3CSh3yLo/edit?usp=sharing)

**Comment by greeceruit** [comment]
> В интерфейсе, кстати, не вижу возможности добавить еще один блочок описания, мне для этого что-то добавить?
Если я правильно понимаю, то кнопка Add text in other language должна сохранять описание на одном языке и создавать такой же блок для другого языка. А кнопочка Save and review - просто сохраняет, не открывая блока для очередного языка 
![Screenshot from 2022-02-26 14-58-38](https://user-images.githubusercontent.com/29063417/155844385-91c355f7-d776-47a5-bff2-1a054f0dc20d.png)

**Comment by vladimir075** [comment]
совершенно верно

**Comment by nicothin** [comment]
Действительно, я как-то проглядел это в подвале :(

Итого:
Разметка для описания: https://github.com/nicothin/nesia/blob/7933f1d8c3a03a5b67a578c2a34e2fa928ccf91e/add.html#L439-L460
Скрипт, обеспечивающий работу всех описаний и кнопки добавления еще одного описания: https://github.com/nicothin/nesia/blob/7933f1d8c3a03a5b67a578c2a34e2fa928ccf91e/add.html#L462-L498
Шаблон, из которого добавляются новые блоки описания: https://github.com/nicothin/nesia/blob/7933f1d8c3a03a5b67a578c2a34e2fa928ccf91e/add.html#L500-L526
Обновленный подвал формы (кнопка продолжения та же самая, только текст внутри другой): https://github.com/nicothin/nesia/blob/7933f1d8c3a03a5b67a578c2a34e2fa928ccf91e/add.html#L528-L531

**Comment by greeceruit** [comment]
@nicothin что-то у меня календарик перекрывается другими полями формы
![Screenshot from 2022-03-20 19-10-18](https://user-images.githubusercontent.com/29063417/159174240-c98e862a-14be-4d35-94ce-a28532f67364.png)

**Comment by nicothin** [comment]
> @nicothin что-то у меня календарик перекрывается другими полями формы

Сложно сказать, сымитировать не получилось. Есть ссыль на какое-то демо вживую?

Мысль: кажется, словно календарь на уровне DOM добавился не перед закрывающим /body, а где-то внутри разметки формы. Если так, лучшее решение -- сделать, таки, обёртки вокруг пар "название + поле" и обертке календаря дать позиционирование и индекс. Можно попробовать сделать это с обратной совместимостью верстки (где есть обертка -- работает по-новому, где нет обертки -- работает как ранее).

**Comment by vladimir075** [comment]
@nicothin у нас есть некоторое расхождение в верстке и макете вот на этом экране
внедренный скрин:
<img width="816" alt="Screenshot 2022-05-24 at 5 36 30 PM" src="https://user-images.githubusercontent.com/17883276/170062109-1191ec39-56ef-4c92-95af-c1e1e9668a13.png">
Требуемое:
<img width="936" alt="Screenshot 2022-05-24 at 5 24 30 PM" src="https://user-images.githubusercontent.com/17883276/170062328-359fecdf-0dce-4f54-9cd9-67145b5151bc.png">
Это третий шаг занесения объекта (там где описание). Поскольку сверстано было по ошибке для первого шага, то видимо Олег внедрил не очень удачно.

**Comment by vladimir075** [comment]
Верстка сделана вот здесь, но ошибочно для первого шага [ ](https://nicothin.pro/nesia/add.html?fbclid=IwAR2jVK05umIoHZt5yDCy6rRXfd9JwpaZ4AN-dfWtNlkzu-1Eq9pi5rNBo4U)

**Comment by greeceruit** [comment]
> > @nicothin что-то у меня календарик перекрывается другими полями формы
> 
> Сложно сказать, сымитировать не получилось. Есть ссыль на какое-то демо вживую?
@nicothin 
Если залогиниться на https://ru.terranesia.com  с данными tashkent@greece.ru    12345$@$@
и перейти по ссылке https://ru.terranesia.com/object/29530122/add/description/  то можно увидеть, как внедрилось....

Календарик внутри формы. Зависит от того, в какую сторону он открывается - вверх или вниз.

**Comment by vladimir075** [comment]
@nicothin у нас так и остались тут некоторые некрасивости
Вот как в дизайне 
<img width="1095" alt="Screenshot 2022-08-01 at 5 48 50 PM" src="https://user-images.githubusercontent.com/17883276/182177330-325a0c35-281b-486f-b523-e287b58d6905.png">
а вот как у нас внедрено
<img width="782" alt="Screenshot 2022-08-01 at 5 46 46 PM" src="https://user-images.githubusercontent.com/17883276/182177465-32d58dbc-a3ce-40f6-84e3-8ea476a9e8a7.png">
то ли шрифт меняется, то ли болда больше, и смещено
