### ISSUE TITLE
Размещение объекта (п.3): в мобильной версии добавить "подвал" с кнопками

### ISSUE THREAD

**Issue by nicothin** [nicothin/nesia#19]
@vladimir075 @nadezdafrolova 

Макет: https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=2947%3A1312
Задача: для малых ширин экрана добавить фиксированный при скролле блок со ссылкой и кнопками.

**Comment by vladimir075** [comment]
да. это относится к логике того что появляется прибитая нижняя часть на стадии занесения объекта, о которой упомянул в комменте к аналогичного экрана в десктопе
