### ISSUE TITLE
Вёрстка стр. Listing

### ISSUE THREAD

**Issue by nicothin** [nicothin/nesia#2]
http://nicothin.pro/nesia/item.html 
(только контентная область, шапка — отдельной задачей).

На 10.06 не завершено.

**Comment by vladimir075** [comment]
Как говорили сердечко Save должно мерцать при скролировании. Пишу просто чтобы мы не забыли. В manual у Надежды есть наглядно видео

**Comment by vladimir075** [comment]
Николай, а Надежду и Марка не добавили? Прошу добавить

**Comment by nicothin** [comment]
Приглашения были отправлены. Их нужно принять (в приходящем на мыло письме есть кнопка-ссылка).

![image](https://user-images.githubusercontent.com/3499680/91018713-986aaf00-e5f8-11ea-8ab7-df48f477cd42.png)

**Comment by vladimir075** [comment]
ясно, спасибо

**Comment by nicothin** [comment]
Добавил 2 цикла мерцания кнопки по первому скроллу вниз.

**Comment by vladimir075** [comment]
@nadezdafrolova вижу что поскольку поле для скролирования является маленьким, сердечко save появляется в правом нижнем углу на секунду и еле заметно. И это при том, что в данном примере есть достаточно большое описание объекта. Помню, что Вы говорили мне о данной проблематике, сейчас увидел ее наглядно. А ведь это сердечко является для нас одним из достаточно серьезных триггеров к монетизации. У меня два вопроса 1) Может нам разместить его под правым блоком сообщения? (я про настольный вариант) 2) Может расположение объекта на карте вынести отдельно под описанием? Таким образом мы увеличим контентную часть про объект? 
Также вопрос не связанный с проблематикой выше. Не предполагается ли у нас что кнопка send offer как то меняет цвет при нажатии плюса или минуса рядом с ценой?

**Comment by nadezdafrolova** [comment]
@vladimir075 

1) Как вариант можно добавить блок карты, думаю это даже будет плюсом для пользователей, блок важный. По поводу like можно сделать следующим образом: добавить блок с картой, и увеличить кнопку в два раза. Если не сработает, тогда менять ее положение. 

2) Да, кнопка имеет два состояния. 

а) Это базовое состояние
<img width="351" alt="image" src="https://user-images.githubusercontent.com/1107340/94551494-56fb9e00-024d-11eb-9f17-107a84121f2f.png">

b) Кнопка после изменения цены 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/1107340/94551567-7692c680-024d-11eb-8465-99eeea47d463.png">

**Comment by vladimir075** [comment]
> * Как вариант можно добавить блок карты, думаю это даже будет плюсом для пользователей, блок важный. По поводу like можно сделать следующим образом: добавить блок с картой, и увеличить кнопку в два раза. Если не сработает, тогда менять ее положение.
> *

@nicothin можно попробовать сверстать самим или от Надежды нужны изменения в макетах?
@nadezdafrolova я так понимаю что квадратики street view и boarders которые сейчас слева от слайдера тоже встанут рядом с картой слева от нее? Может все таки прорисовать нам макет для Николая? Наверняка там еще какой то заголовок понадобится к блоку...

**Comment by vladimir075** [comment]
> 2\. Да, кнопка имеет два состояния.
> 
> а) Это базовое состояние
> <img alt="image" width="351" src="https://user-images.githubusercontent.com/1107340/94551494-56fb9e00-024d-11eb-9f17-107a84121f2f.png">
> 
> b) Кнопка после изменения цены
> <img alt="image" width="334" src="https://user-images.githubusercontent.com/1107340/94551567-7692c680-024d-11eb-8465-99eeea47d463.png">

@nicothin а у нас это состояние кнопки есть? не вижу его при нажатии на плюс и минус

**Comment by nicothin** [comment]
Блок предложения цены: следить за кликом на + или -, на кнопке рядом убирать класс b-btn-2--secondary
Ждать дизайна (карта и borders будут вынесены отдельно).

**Comment by nicothin** [comment]
>Блок предложения цены: следить за кликом на + или -, на кнопке рядом убирать класс b-btn-2--secondary

выполнено, станет доступно после деплоя.

**Comment by nicothin** [comment]
>Добрый день, сделала вариант с картой + увеличила кнопку Save, посмотреть можно вот здесь
https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=333%3A61

готово
