### ISSUE TITLE
Сообщения (п.10): соответствие макету

### ISSUE THREAD

**Issue by nicothin** [nicothin/nesia#24]
@vladimir075 @nadezdafrolova 

Макет: https://www.figma.com/file/OMi3vX6CvJMMciuJ7rIvSI/Terra?node-id=2943%3A1090
Существующая вёрстка: https://nicothin.pro/nesia/messages.html

Задачи:

1. Вопрос от продавца: добавить текстовой блок 
![image](https://user-images.githubusercontent.com/3499680/169650429-d854f641-1fdd-48a2-b6c0-a896d069043e.png)
2. Вопрос от покупателя: сменить верстку по макету

**Comment by vladimir075** [comment]
этот кусок мы совсем недавно уже сделали вне очереди, issue можно закрыть
