### ISSUE TITLE
Вёрстка стр. My Listings

### ISSUE THREAD

**Issue by nicothin** [nicothin/nesia#3]
http://nicothin.pro/nesia/my-listings.html

Псевдомодалки можно увидеть, если развернуть второй блок локации и потыкать в его кнопки.

**Comment by vladimir075** [comment]
![Screen Shot 2020-07-13 at 2 41 08 PM](https://user-images.githubusercontent.com/17883276/87300700-f9419a80-c516-11ea-8ffd-e010793c643a.png)
Если не сложно, Send зелененький исправить на Sent. А то одна буква меняет смысл. Чтобы девелопер потом не запутался.

**Comment by vladimir075** [comment]
![Screen Shot 2020-07-13 at 2 50 38 PM](https://user-images.githubusercontent.com/17883276/87301443-42461e80-c518-11ea-93a5-34c3e011b609.png)
Смущает то, что не помещается фраза Are you still interested? Полная фраза здесь достаточно критична для начала диалога. Можно конечно ее сократить типа Are you interested?, например по русски Вы заинтересованы? Но на всякий случай спрашиваю есть ли какие то другие решения для того чтобы не стесняться в количестве букв )

**Comment by vladimir075** [comment]
![Screen Shot 2020-07-13 at 2 55 19 PM](https://user-images.githubusercontent.com/17883276/87301826-e9c35100-c518-11ea-881f-2b35fc0e2b43.png)
Здесь кнопки Contact и Open message почему то появляются при mouse over (соотвественно в мобилке не появляются вообще). Это неправильно. Они должны там просто быть )

**Comment by vladimir075** [comment]
![Screen Shot 2020-07-13 at 2 57 18 PM](https://user-images.githubusercontent.com/17883276/87301971-2f801980-c519-11ea-9139-7cc2a786ab4c.png)
Марк, как мы с Вами решили, здесь не не разделяем на два под отдела тех, кто сделал save и кто сделал follow price change. Помещаем обе категории в Save listing by (назовем видимо Saved to favourites by 2(?)) 
При этом тот кто сделал follow price change  у них объект должен попадать в Favourites

**Comment by nicothin** [comment]
## Пункт 1
> Если не сложно, Send зелененький исправить на Sent. А то одна буква меняет смысл. Чтобы девелопер потом не запутался.

Исправил.

## Пункт 2

>Смущает то, что не помещается фраза Are you still interested? Полная фраза здесь достаточно критична для начала диалога. Можно конечно ее сократить типа Are you interested?, например по русски Вы заинтересованы? Но на всякий случай спрашиваю есть ли какие то другие решения для того чтобы не стесняться в количестве букв )

1. сделать область отправляемого текста многострочной
2. сделать кнопку отправки с иконкой, не текстом (пока сделал так)

![image](https://user-images.githubusercontent.com/3499680/93904900-02af6600-fd03-11ea-8415-c785c5f537e1.png)

## Пункт 3

>Здесь кнопки Contact и Open message почему то появляются при mouse over (соотвественно в мобилке не появляются вообще). Это неправильно. Они должны там просто быть )

Для устройств с тач-взаимодействием кнопки видны сразу (не на ширину экранов реагируют, а на тип ввода, ибо это безопаснее). Но это для более-менее широких экранов (480+). 
В дизайне для мобилок этих кнопок просто нет. Могу на совсем узких экранах показать кнопки строкой ниже (под датой, выравнивание вправо), делать?
