### ISSUE TITLE
Вёрстка стр. Auction

### ISSUE THREAD

**Issue by nicothin** [nicothin/nesia#4]
https://nicothin.pro/nesia/auction.html

Небольшие изменения относительно дизайна, вызванные заботой о переполнении тестом.

**Comment by vladimir075** [comment]
Николай, а в чем заключаются изменения? Как то не нашел.
И там еще есть состояние Contact now, его тоже не увидел.

**Comment by vladimir075** [comment]
Еще у меня в 6ом айфоне смещаются в подвале язык и валюта

**Comment by nicothin** [comment]
@vladimir075 

> Николай, а в чем заключаются изменения? Как то не нашел.

Некоторые ширины ячеек в таблице с ценой предложения (переполнение большой ценой плохо адаптировалось, чуть поменял).
Цвет ссылки Cancel в блоке удаления предложения (?) сделал зеленый, как в мобилке (для десктопа прорисован красный).

> И там еще есть состояние Contact now, его тоже не увидел.

Там три блока с некопируемым из фигмы текстом (вставил типографскую «рыбу»). Сделал один блочок, ибо 2 и 3 не отличаются:

![image](https://user-images.githubusercontent.com/3499680/87466303-b66aea00-c61e-11ea-8203-0f055afc467c.png)

Но кнопочку, таки, сделал. Просто скрыл. Если убрать сокрытие, то вот она:

![image](https://user-images.githubusercontent.com/3499680/87466474-f9c55880-c61e-11ea-99b2-4156e46c579f.png)

Сейчас, правда, заметил, что там длина блока с текстом ограничена, сегодня подпилю.

**Comment by nicothin** [comment]
Айфон 6 попробую эмулировать, погляжу на подвал.
