### ISSUE TITLE
Вёрстка стр. Messages

### ISSUE THREAD

**Issue by nicothin** [nicothin/nesia#6]
Состояния (мод. окна)  по тычкам в соотв. кнопки.
Проблема с двойными модальными окнами (покупка контакта) для настольных: лажовый подсчёт добавляемого на `body` внутр. правого отступа. Что делать ХЗ. Надеюсь не будет 2-х модальных окон открыто одновременно.
Добавлено некоторое кол-во временного JS.

http://nicothin.pro/nesia/messages.html

**Comment by vladimir075** [comment]
не очень понял про что это. если есть какая то проблематика, может нам подскажет Надежда? @nicothin кстати она вроде добавилась в проект, а прикрепить ее я так и не могу

**Comment by nicothin** [comment]
Быть может, @nadezdafrolova нам с этим поможет )

Отправил Надежде инвайт еще раз, ибо не нашел ее в списке разработчиков.

**Comment by nadezdafrolova** [comment]
Не поняла описанной проблемы, поясните детальнее пожалуйста

**Comment by nicothin** [comment]
Предлагаю созвониться для демки.
Ну или скажите будет ли состояние, когда из модального окна открывается второе мод. окно, а первое остаётся.

**Comment by vladimir075** [comment]
@nadezdafrolova Надежда?

**Comment by nicothin** [comment]
Двойного модального окна не будет.
При покупке контакта менять содержимое модального окна, а не открывать новое.

**Comment by nicothin** [comment]
>При покупке контакта менять содержимое модального окна, а не открывать новое.

Сделано, будет доступно после деплоя
